# Generated by Django 3.2.12 on 2022-02-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='simple_images/profile_default.png', upload_to='mediafiles/photo/', verbose_name='Profile Photo'),
        ),
    ]
